name: O Fim - Merge

on:
  workflow_dispatch:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  start:
    name: Merge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: validate step
        id: validacao
        run: |
          currentstep=$(cat .github/CONFIG/step.txt)
          echo "::set-output name=currentstep::$currentstep"

      - name: Create an issue
        if: ${{ steps.validacao.outputs.currentstep == '4' }}      
        uses: actions-ecosystem/action-create-issue@v1
        with:
          github_token: ${{ secrets.ISSUE_SECRET }}
          title: E chegamos ao fim do desafio!!!
          body: |
            ## E não é que você terminou?

            Agora sua alteração foi incluida na branch main, e seu trabalho foi concluido. :partying_face:

            Oque você achou desse desafio? Fácil? Dificil?

            E ai? Vamos fazer os demais desafios? Em breve mais um será liberado para você. Espero te ver 
            finalizando cada um dos testes eim?!

            Mais uma vez, meus parabéns, e bons estudos!!
            ![hula_loop_octodex](https://octodex.github.com/images/jetpacktocat.png)          

      - name: Atualizar Issue Desafio
        if: ${{ steps.validacao.outputs.currentstep == '4' }}  
        run: |
          issuenumber=$(cat .github/CONFIG/issue.txt)
          curl -X DELETE -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.ISSUE_SECRET }}" https://api.github.com/repos/tempdemo2022/Participe/issues/$issuenumber/labels
          curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.ISSUE_SECRET }}" https://api.github.com/repos/tempdemo2022/Participe/issues/$issuenumber/labels -d '{"labels":["desafio2"]}'